//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group4_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentMetadata
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocumentMetadata()
        {
            this.PatientRecord = new HashSet<PatientRecord>();
        }
    
        public string docID { get; set; }
        public string userID { get; set; }
        public string docName { get; set; }
        public Nullable<System.DateTime> dateOfCreation { get; set; }
        public string versions { get; set; }
        public string FileUrl { get; set; }  // Ensure this property exists

        public virtual iCareWorker iCareWorker { get; set; }
        public virtual ModificationHistory ModificationHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PatientRecord> PatientRecord { get; set; }
    }
}
