//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group4_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class iCareAdmin
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public iCareAdmin()
        {
            this.iCareWorker = new HashSet<iCareWorker>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> dateHired { get; set; }
        public Nullable<System.DateTime> dateFinished { get; set; }
    
        public virtual iCareUser iCareUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<iCareWorker> iCareWorker { get; set; }
    }
}
