//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group4_iCAREAPP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TreatmentRecord
    {
        public string treatmentID { get; set; }
        public string description { get; set; }
        public System.DateTime treatmentDate { get; set; }
        public string patientID { get; set; }
        public string workerID { get; set; }
        public string drugID { get; set; }
        public string docID { get; set; }
    
        public virtual iCareWorker iCareWorker { get; set; }
        public virtual PatientRecord PatientRecord { get; set; }
        public virtual DrugsManagementSystem DrugsManagementSystem { get; set; }
        public virtual DocumentMetadata DocumentMetadata { get; set; }
    }
}
